name: Continuous Build

on:
  push: { }
  workflow_dispatch: { }

jobs:
  pipeline:
    name: Build
    runs-on: [self-hosted, default]

    steps:
    - name: Setup Java JDK 21
      uses: actions/setup-java@v3
      with:
        runs-on: cloud-native-engineering-default
        java-version: 21
        distribution: corretto
        overwrite-settings: false #keep EPO specific m2_settings.xml provided by runner docker image

    - name: Checkout Source Code
      uses: actions/checkout@v3

    - name: Install
      run: mvn clean deploy
