name: Vulnerability Scan

on:
  push:
    # Specify here default branch. Optionally the list can be extended with protected branches.
    branches: [ master ]

  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
    types: [ opened, reopened, synchronize ]
    paths-ignore: [ '**/*.md', '**/*.txt' ]

  # Trigger workflow at scheduled time.
  # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  schedule:
    - cron: '4 5 * * 0'

  # Manually trigger workflow.
  workflow_dispatch: {}

jobs:
  scan:
    name: Scan
    uses: platform/workflow-collection/.github/workflows/vulnerability-scan.yaml@4.15
    with:
      log-level: INFO
      actions-ref: v1.4 # you can find the latest releases here https://git.epo.org/platform/gh-actions/releases
      build-tool: mvn
      java-version: 21
